[aws]
  [aws.sqs]
  template = "../../template/sqs.md"

    [aws.sqs.filter]
    in = ""
    out = [".*[0-9]{8}", ".*test.*", ".*_[0-9a-zA-Z]{16}"]

    [aws.sqs.supplement."example-develop-queue01"]
    usecase = "開発環境用キュー１"
    environment = "develop"

    [aws.sqs.supplement."example-queue01"]
    usecase = "本番環境用キュー１"
    environment = "production"

    [aws.sqs.supplement."example-staging-queue01"]
    usecase = "ステージング環境用キュー１"
    environment = "staging"

    [aws.sqs.supplement."example-queue02"]
    usecase = "本番環境用キュー２"
    environment = "production"

  [aws.ec2]
  template = "../../template/ec2.md"

    [aws.ec2.filter]
    in = ""
    out = []

    [aws.ec2.supplement."i-0123456789"]
    usecase = "開発環境用インスタンス"
    environment = "develop"

  [aws.rds]
  template = "../../template/rds.md"

    [aws.rds.filter]
    in = ""
    out = []

    [aws.rds.supplement."i-0123456789"]
    usecase = "開発環境用インスタンス"
    environment = "develop"

  [aws.dynamodb]
  template = "../../template/dynamodb.md"

    [aws.dynamodb.filter]
    in = ""
    out = []

    [aws.dynamodb.supplement."m_movie"]
    usecase = "ムービー"
    environment = "develop"
